# Generated by Django 6.0.3 on 2026-04-11 22:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('google', 'Google'), ('bedrock', 'AWS Bedrock')], default='anthropic', max_length=50)),
                ('input_cost_per_1m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('output_cost_per_1m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cache_write_cost_per_1m', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cache_read_cost_per_1m', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('allowed_for_free', models.BooleanField(default=True)),
                ('allowed_for_paid', models.BooleanField(default=True)),
                ('context_window', models.IntegerField(default=200000)),
                ('max_output_tokens', models.IntegerField(default=8192)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ailogs_aimodel',
                'ordering': ['input_cost_per_1m'],
            },
        ),
        migrations.CreateModel(
            name='SiteAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_free_credits', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10)),
                ('step_model_config', models.JSONField(blank=True, default=dict)),
                ('default_free_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_agentic.aimodel')),
                ('default_paid_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_agentic.aimodel')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
                'db_table': 'ailogs_siteaiconfig',
            },
        ),
        migrations.CreateModel(
            name='UserAIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_monthly_credits', models.DecimalField(decimal_places=6, default=Decimal('2.000000'), max_digits=10)),
                ('purchased_credits', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('credits_reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_agentic.aimodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AI Profile',
                'db_table': 'ailogs_useraiprofile',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('workflow', models.CharField(db_index=True, max_length=100)),
                ('node', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=255)),
                ('input_summary', models.TextField(blank=True, default='')),
                ('output_json', models.JSONField(default=dict)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.IntegerField(blank=True, null=True)),
                ('cache_creation_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('input_cost_per_1m_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('output_cost_per_1m_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cache_write_cost_per_1m_at_time', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('cache_read_cost_per_1m_at_time', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('used_free_credits', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('used_paid_credits', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('provider_request_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_type', models.CharField(blank=True, choices=[('', 'None'), ('credit_limit', 'Credit Limit'), ('api_error', 'API Error'), ('validation', 'Validation'), ('context_overflow', 'Context Overflow'), ('unknown', 'Unknown')], default='', max_length=20)),
                ('request_time', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='django_agentic.aimodel')),
                ('entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ailogs_aiusagelog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'created_at'], name='ailogs_aius_model_n_434025_idx'), models.Index(fields=['workflow', 'created_at'], name='ailogs_aius_workflo_7e02c2_idx'), models.Index(fields=['user', 'created_at'], name='ailogs_aius_user_id_cd756c_idx')],
            },
        ),
    ]
