# Generated by Django 6.0.3 on 2026-04-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('chat', 'Chat / Generation'), ('embedding', 'Embedding'), ('transcription', 'Transcription'), ('image', 'Image Generation')], db_index=True, default='chat', max_length=20),
        ),
    ]
