# Generated by Django 6.0.3 on 2026-04-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_agentic', '0002_add_model_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='django_ai_a_model_n_053a01_idx',
            old_name='ailogs_aius_model_n_434025_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='django_ai_a_workflo_9b3be0_idx',
            old_name='ailogs_aius_workflo_7e02c2_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='django_ai_a_user_id_6d10e0_idx',
            old_name='ailogs_aius_user_id_cd756c_idx',
        ),
        migrations.AlterModelTable(
            name='aimodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='aiusagelog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='siteaiconfig',
            table=None,
        ),
        migrations.AlterModelTable(
            name='useraiprofile',
            table=None,
        ),
    ]
