# Generated by Django 6.0.3 on 2026-04-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai', '0004_seed_default_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(db_index=True, default='anthropic', help_text='Provider name (must match a registered provider in providers.py). Built-in: anthropic, openai. Custom providers registered via register_provider().', max_length=50),
        ),
    ]
